### ISSUE TITLE
After upload file and create database ?

### ISSUE THREAD

**Issue by hfrance** [dmd2222/SMSHub-PHP-Server#1]
Hello,

I have uploaded the file and create the database in mysql, I have the android app setup too, domain url is ok. what is the next step ?

the send URL in the app forward to witch php ?

**Comment by hfrance** [comment]
I am just not sure to understant the logical... what commande we need to push to the service.php for send sms ?

**Comment by dmd2222** [comment]
Hi hfrance,

Well you have to do this steps.
1. Upload the php-Files to your webspace.
2. Edit the config file. (config_device_id_secret,config_admin_email,config_debugging_on,config_debugging_mode)
3. After that, you can use service.php php-file as the api. (domain.com/service.php)
(If you open it in the Browser you see "Err 401 - Tip: Try action=help as POST or GET"?)
4. Now you can send GET or POST requests to the api (see step 3).
5.optional. If you have set up, the app, you installed it, then you should be able to find tho options.
(the gear symbol)
6. There you can find the Server URL... set this URL you have got in step 3.
6.1. Set the DeviceID to one of your "config_device_id_secret" (see step 2)
6.2 Click "Save configuration", in the app.

Test it: with Number, Message (MessageID optional), you can test the service. May you use your own number to test it. Click Send sms.

Result: Now you have a possibility to send sms's through the php api to your phone.

If you have any futhure questions, please ask. 
May you will support this project or help me developing this project: https://www.patreon.com/marcoschwald

**Comment by dmd2222** [comment]
If you have futhure problems please open a new issue.

**Comment by hfrance** [comment]
Thank for your help, Keep up your good work.

Merci.
